name: check_triggers
on:
  workflow_call:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

jobs:
  job1_checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: execute checkout dummy-swc-1
        uses: actions/checkout@v4
      - run: echo "dummy-swc-1" 
      - run: echo "dummy-swc-2" 

  job2_just_checking:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - run: echo "dummy-swc-3" 
      - run: echo "dummy-swc-4" 
